name: groomlyfe
description: A new Flutter project.

version: 1.0.0+1

environment:
#  sdk: ">=2.17.1 <3.0.0"
   sdk: ">=2.15.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  rxdart: ^0.27.7
  app_settings: ^4.1.8
  onesignal_flutter: ^3.4.2
  video_player: ^2.4.8
  youtube_player_flutter: ^8.1.1
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.2.1
  cached_network_image: ^3.2.3
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  cloud_firestore: ^4.1.0
  firebase_database: ^10.0.6
  google_sign_in: ^5.4.2
  video_thumbnail: ^0.5.3
  transparent_image: ^2.0.0
  flutter_local_notifications: ^12.0.4
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  another_flushbar: ^1.12.29
  firebase_storage: ^11.0.6
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  carousel_slider: ^4.1.1
  group_button: ^5.2.2
  toast: ^0.3.0
  flutter_chips_input: ^2.0.0
  flutter_speed_dial: ^6.2.0
  datetime_picker_formfield: ^2.0.1
  date_format: ^2.0.7
  autocomplete_textfield: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  flutter_custom_clippers: ^2.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  percent_indicator: ^4.2.2
  flutter_foreground_task: ^3.10.0
  visibility_detector: ^0.3.3
  #flutter_foreground_plugin: ^0.8.0
  #flutter_pin_code: ^1.0.1
  #  flutter_screen_recording: ^2.0.7
  flutter_braintree: ^2.3.1
  provider: ^6.0.4
  agora_rtc_engine: ^5.2.0
  permission_handler: ^10.2.0
  internet_connection_checker: ^1.0.0+1
  cached_video_player: ^2.0.3
  flutter_widget_from_html_core: ^0.9.0+2
  flutter_fgbg: ^0.2.2
  wakelock: ^0.6.2
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.2.16
  # camera_deep_ar: ^0.0.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

#dependency_overrides:
#  firebase_core_platform_interface: ^4.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/back.mp4
    - assets/category/
  fonts:
    - family: Ewert
      fonts:
        - asset: fonts/Ewert-Regular.ttf
    - family: Nova Round
      fonts:
        - asset: fonts/NovaRound-Regular.ttf
    - family: phenomena-bold
      fonts:
        - asset: fonts/Phenomena-Bold.ttf
    - family: phenomena-regular
      fonts:
        - asset: fonts/Phenomena-Regular.ttf
